### ISSUE TITLE
Are you planning to release a training code ?

### ISSUE THREAD

**Issue by rishikksh20** [mct10/RepCodec#4]
Hi @mct10 ,
RepCodec performance on Whisper features looks good and I am highly impressive by your approach, so I am planning to train RepCodec on non-english languages using Whisper's feature. Do you have any timeline when to release a training code for this repo?

Thanks

**Comment by mct10** [comment]
Hi, thanks for your interests!
We are now waiting for the decision of our paper, which will be released on Jan 15.
FYI, our training code actually is very similar to [AudioDec](https://github.com/facebookresearch/AudioDec). You can have a look if interested.
Thanks.

**Comment by rishikksh20** [comment]
Hi @mct10 
![image](https://github.com/mct10/RepCodec/assets/4656872/6e10e720-a393-4b08-8195-f3b76a0440a0)

`generator_loss = vq_loss + 45 * reconstruction_loss`
getting these on tensorboard, perplexity keeps on increasing. Is this behavior being normal?

**Comment by mct10** [comment]
Hi, I think it is normal. I got similar behaviors.

**Comment by rishikksh20** [comment]
ok thanks

**Comment by yaya-sy** [comment]
Hi, any news on the release of the official training script?

**Comment by mct10** [comment]
Hi, we are working on it and plan to release in about 2 weeks.

**Comment by rishikksh20** [comment]
finally done
