### ISSUE TITLE
The possibility of same method on visual modality

### ISSUE THREAD

**Issue by youngsheen** [mct10/RepCodec#8]
HI, excellent work! 

Glad to see the VQ + SSL method surpass K-Means + SSL method. Recently, we also find that discrete units method can surprisingly works well  on images (red DiGIT at https://github.com/DAMO-NLP-SG/DiGIT). Maybe you can apply the repcodec on images as well.

**Comment by mct10** [comment]
Hi, thanks for sharing your thoughts! That sounds interesting, we may take a look when we have time.
