### ISSUE TITLE
Where is the inference.py file?

### ISSUE THREAD

**Issue by Qoboty** [mct10/RepCodec#9]
Hi, inference.py is missing? where is the inference.py file
<img width="721" alt="image" src="https://github.com/user-attachments/assets/41bab9a9-c1e0-4d02-9b98-0bde66272f4c">

**Comment by mct10** [comment]
Hi, this example refers to running inference using the **vocoder**, not RepCodec.
So, please use [this inference.py from speech-resynthesis](https://github.com/facebookresearch/speech-resynthesis/blob/main/inference.py) to run inference for the vocoder.
If you want to run inference with RepCodec, please follow [this](https://github.com/mct10/RepCodec?tab=readme-ov-file#command-line-usage) or [this](https://github.com/mct10/RepCodec?tab=readme-ov-file#python-usage).
